name: 'Lock Issues'

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  issues: write

concurrency:
  group: lock

jobs:
  lock-issues:
    runs-on: ubuntu-latest
    steps:
      - name: 'Lock Issues'
        uses: dessant/lock-threads@851cffe46851ddd2051ea7147ebdc995113241c3 # v6.0.1
        with:
          github-token: ${{ github.token }}
          issue-inactive-days: '30'
          process-only: 'issues'
          log-output: true
